package woofer.gui;

import javafx.application.Platform;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.ScrollPane;
import javafx.scene.control.TextField;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.VBox;
import woofer.WooferService;
import woofer.exception.WooferException;

/**
 * Controller for Woofer's main JavaFX window.
 */
public class MainWindow extends AnchorPane {
    /** Scrollable area containing the conversation. */
    @FXML
    private ScrollPane scrollPane;

    /** Vertical container holding the conversation's dialog boxes. */
    @FXML
    private VBox dialogContainer;

    /** Text field where the user enters a command. */
    @FXML
    private TextField userInput;

    /** Button that submits the command in {@link #userInput}. */
    @FXML
    private Button sendButton;

    /** Application service used to process user commands. */
    private WooferService wooferService;

    /**
     * Sets up automatic scrolling and displays Woofer's greeting.
     */
    @FXML
    private void initialize() {
        dialogContainer.heightProperty().addListener((observable, oldHeight, newHeight) ->
                scrollToBottom());
        appendWooferMessage("Hello! I'm Woofer.\nWhat can I do for you?");
    }

    /**
     * Connects the controller to the shared application logic.
     *
     * @param service service that parses and executes Woofer commands.
     */
    public void setWooferService(WooferService service) {
        wooferService = service;
        if (service.hasLoadingError()) {
            appendWooferMessage("Warning: Could not load saved tasks. "
                    + "Starting with an empty list.");
        }
        userInput.requestFocus();
    }

    /**
     * Processes a command submitted by pressing Enter or clicking Send.
     */
    @FXML
    private void handleUserInput() {
        String input = userInput.getText().trim();
        if (input.isEmpty()) {
            return;
        }

        appendUserMessage(input);
        userInput.clear();

        try {
            WooferService.Response response = wooferService.execute(input);
            appendWooferMessage(response.message());
            if (response.exits()) {
                disableInput();
            }
        } catch (WooferException exception) {
            appendWooferMessage("OOPS!!! " + exception.getMessage());
        }
    }

    /**
     * Adds a user message to the conversation.
     *
     * @param message text entered by the user.
     */
    private void appendUserMessage(String message) {
        dialogContainer.getChildren().add(DialogBox.getUserDialog(message));
        scrollToBottom();
    }

    /**
     * Adds a Woofer response to the conversation.
     *
     * @param message response generated by Woofer.
     */
    private void appendWooferMessage(String message) {
        dialogContainer.getChildren().add(DialogBox.getWooferDialog(message));
        scrollToBottom();
    }

    /**
     * Scrolls after JavaFX has laid out the newly added conversation message.
     *
     * <p>Scheduling this update prevents later messages, including repeated list responses,
     * from being placed below the visible viewport.</p>
     */
    private void scrollToBottom() {
        Platform.runLater(() -> scrollPane.setVvalue(1.0));
    }

    /**
     * Prevents further commands after the user sends the bye command.
     */
    private void disableInput() {
        userInput.setDisable(true);
        sendButton.setDisable(true);
        userInput.setPromptText("Woofer has stopped. Close the window to exit.");
    }
}
